Update README
savitar-exchange/swap-sdk pull request #1
Opened 2020-09-22 10:27 UTC by jloup

2020-09-22 18:04 UTC, savitar-dev commented on README.md
> +import * as savitar from 'swap-sdk';
remplacer savitar par Swap

2020-09-22 18:05 UTC, savitar-dev commented on README.md
> +- `payment_type` : `exchange`
optional

2020-09-22 18:11 UTC, savitar-dev requested changes

2020-09-22 18:11 UTC, savitar-dev commented on README.md
> +- `payment_type` : `exchange`
remove payment_type

2020-09-22 20:08 UTC, jloup commented on README.md
> +import * as savitar from 'swap-sdk';
done

2020-09-22 20:08 UTC, jloup commented on README.md
> +- `payment_type` : `exchange`
done

2020-09-22 20:08 UTC, jloup commented on README.md
> +- `payment_type` : `exchange`
done

2020-09-24 01:17 UTC, savitar-dev approved these changes

2020-09-24 01:17 UTC, merged